import Container from "@/components/ui/Container";


export const processSteps = [
  {
    step: "01",
    title: "Image Acquisition",
    description: "Patient is scanned via CT, MRI, or X-ray, generated by the modality.",
  },
  {
    step: "02",
    title: "PACS Upload",
    description: "Images are automatically routed to your PACS for AI processing.",
  },
  {
    step: "03",
    title: "AI Processing",
    description:
      "Our AI engine analyzes images in seconds, flagging anomalies and generating a priority score.",
  },
  {
    step: "04",
    title: "Radiologist Review",
    description:
      "The radiologist reviews the AI-annotated study and finalizes the report inside the viewer.",
  },
  {
    step: "05",
    title: "Final Report Delivery",
    description: "The finalized report is delivered to the referring clinician via EMR or PDF.",
  },
];

export default function Process() {
  return (
    <section className="bg-surface py-16 sm:py-20">
      <Container>
        <h2 className="mx-auto max-w-xl text-center text-3xl font-bold tracking-tight text-ink sm:text-4xl">
          How <span className="text-primary">Radiomind</span> works
        </h2>

        <div className="mt-14 grid gap-8 sm:grid-cols-3 lg:grid-cols-5">
          {processSteps.map((step) => (
            <div key={step.step} className="relative text-center">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-primary font-display text-lg font-bold text-white">
                {step.step}
              </div>
              <h3 className="mt-4 text-sm font-semibold text-ink">{step.title}</h3>
              <p className="mt-2 text-xs leading-relaxed text-slate">{step.description}</p>
            </div>
          ))}
        </div>
      </Container>
    </section>
  );
}
